spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yahyanouali/ConfigData
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/